spring.application.name=payment-execution
server.port=8081

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

stripe.api.key=${STRIPE_API_KEY}
paypal.client.id=${PAYPAL_CLIENT_ID}

paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

java.net.preferIPv4Stack=true