spring.application.name=payment-execution
server.port=8051

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

stripe.api.key=${STRIPE_API_KEY}
paypal.client.id=${PAYPAL_CLIENT_ID}

paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

java.net.preferIPv4Stack=true

# ========== CIRCUIT BREAKER CONFIG ==========
resilience4j.circuitbreaker.instances.razorpay.sliding-window-size=10
resilience4j.circuitbreaker.instances.razorpay.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.razorpay.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.razorpay.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.razorpay.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.stripe.sliding-window-size=10
resilience4j.circuitbreaker.instances.stripe.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.stripe.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.stripe.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.stripe.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.paypal.sliding-window-size=10
resilience4j.circuitbreaker.instances.paypal.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paypal.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paypal.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paypal.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.razorpay.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.stripe.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.paypal.automatic-transition-from-open-to-half-open-enabled=true