# Server
server.port=8050
spring.application.name=payment-orchestrator

# Execution Service URL
execution.service.url=http://localhost:8051

# ========== PROVIDER SELECTION RULES ==========
payment.provider.default=razorpay
payment.rules.threshold-low=10000
payment.rules.threshold-high=100000
payment.rules.provider-low=razorpay
payment.rules.provider-medium=stripe
payment.rules.provider-high=paypal

# ========== POSTGRESQL ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=Ayaan@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========== REDIS ==========
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Cache TTLs (in seconds)
cache.ttl.rules=300
cache.ttl.transaction=60
cache.ttl.user-transactions=30

# ========== FRAUD RULES ==========
fraud.rules.file=config/fraud-rules.json

# ========== RETRY + EXPIRY ==========
retry.scheduler.interval-ms=10000
retry.batch-size=50
retry.expiry-minutes=15
retry.max-attempts=5